name: Epitech Actions Workflow

on:
  push:
    branches:
      - main # This is the branch you want to make all your tests

jobs:

  style_check:
    runs-on: ubuntu-23.10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone coding style checker repository
        run : |
          git clone https://github.com/Epitech/coding-style-checker.git /tmp/style-checker

      - name: Run coding style checker
        run: |
          chmod +x /tmp/style-checker/coding-style.sh
          /tmp/style-checker/coding-style.sh . . > epitech-actions-output-style.txt
          errors=$(grep -o '^[0-9]\+' epitech-actions-output-style.txt | tail -n 1)
          if [ "$errors" -gt 0 ]; then
            file_content=$(tail -n 1 epitech-actions-output-style.txt)
            echo "::error::${file_content}"
            exit 1
          else
          echo "::notice::No coding style error reported. Good Job !"
          fi

  test:
    runs-on: ubuntu-23.10
    needs: style_check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install criterion for tests
        run: |
          git clone https://github.com/matteoepitech/EpitechActions.git
          cd EpitechActions
          chmod +x install_criterion.sh
          ./install_criterion.sh

      - name: Verify and run tests
        run: |
          if grep -q '^tests_run:' Makefile; then
            make tests_run
          else
          echo "::warning::No tests_run rule found in Makefile."
          fi
