name: Epitech Actions Workflow

on:
  push:
    branches:
      - main # This is the branch you want to make all your tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify and run tests
        run: |
          if grep -q '^tests_run:' Makefile; then
            make tests_run
          else
            echo "No tests_run rule found in Makefile."
          fi
  
  style_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone coding style checker repository
        run : |
          git clone https://github.com/Epitech/coding-style-checker.git /tmp/style-checker

      - name: Run coding style checker
        run: |
          chmod +x /tmp/style-checker/coding-style.sh
          /tmp/style-checker/coding-style.sh . . > epitech-actions-output-style.txt
          errors=$(grep -o '[0-9]*' epitech-actions-output-style.txt)
          if [ "$errors" -gt 0 ]; then
            echo "::error:: $errors coding style error(s) reported."
            exit 1
          fi
